[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[terminal.shell]
program = "/home/gt/.local/bin/tmuxtart"

[env]
TERM = "xterm-256color"

[font]
normal = {family ="SauceCodePro NF"}
# normal = {family ="Maple Mono NF"}
size = 10

[window]
padding = {x = 4, y = 2}
startup_mode = "Maximized"
decorations = "None"
opacity = 0.99

[colors]
# primary.background = '#333333'
# primary.background = '#2d2d2d'
# primary.background = '#282828'
# primary.background = '#232323'
# primary.background = '#1e1e1e' 
# primary.background = '#191919'
primary.background = '#141414'
# primary.background = '#0f0f0f'

# primary.foreground = '#1793d1'
# primary.foreground = '#1793d1'
# primary.foreground = '#1484bc'
# primary.foreground = '#1275a7'
# primary.foreground = '#106692'
# primary.foreground = '#0d587d'
# primary.foreground = '#0b4968'
# primary.foreground = '#093a53'

[cursor]
style.shape = "Beam"
vi_mode_style.shape = "Block"

